### ISSUE TITLE
_handleTap() called again while calling togge() on Firefox

### ISSUE THREAD

**Issue by ashkhn** [azumbrunnen/paper-expansion-panel#1]
Hey
I was just playing aound with the project and noticed that the panel does not collapse on clicking the paper buttons in Firefox. I added  console log statements to figure out the issue and it seems that the `_handleTap` and hence `toggle()` were called again after the first toggle call. 
Not sure if this is an issue with Firefox because I couldn't find any issues with the code..

Using Firefox 41 on Ubuntu.

**Comment by azumbrunnen** [comment]
I just noticed the same. That's very odd. Thanks for looking into it. I will have a closer look at this, this week. Maybe .closest is causing the issues calling the component's "toggle" method from the console seems to work just fine.

**Comment by azumbrunnen** [comment]
This issue has been fixed now. Firefox was sending two events at the same time which is why the panel expanded again right after opening it (making it look like it didn't do anything at all)
